<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>Philips.CT.Host.ImageDisplay.Shell</RootNamespace>
    <AssemblyName>Philips.CT.Host.ImageDisplay.App</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ImageDisplay\Philips.CT.Host.ImageDisplay.Impl.csproj" />
    <ProjectReference Include="..\..\ExtInf\ImageDisplay\Philips.CT.Host.ImageDisplay.Inf.csproj" />
  </ItemGroup>

</Project>
